import { insertProducts } from './dataToFirebase';

export const data = {
  Products: [
    {
      name: 'Free shirt',
      slug: 'free-shirt',
      category: ' shirts',
      image: '/images/shirt1.webp',
      image2: '/images/shirt1.webp',
      image3: '/images/shirt1.webp',
      price: 150,
      brand: 'Addidas',
      rating: '4.5',
      countInStock: 10,
      description: 'A popular shirt',
      numReviews: 13,
    },
    {
      name: 'Fit shirt',
      slug: 'fit-shirt',
      category: 'shirts',
      image: '/images/shirt2.webp',
      image2: '/images/shirt2.webp',
      image3: '/images/shirt2.webp',
      price: 200,
      brand: 'Nike',
      rating: '4',
      countInStock: 20,
      numReviews: 13,
      description: 'A popular fit shirt',
    },
    {
      name: 'Slim shirt',
      slug: 'slim-shirt',
      category: 'shirts',
      image: '/images/shirt3.webp',
      image2: '/images/shirt3.webp',
      image3: '/images/shirt3.webp',
      price: 100,
      brand: 'Raymond',
      rating: '4.5',
      countInStock: 15,
      numReviews: 13,
      description: 'A popular slim shirt',
    },
    {
      name: 'Golf Pants',
      slug: 'golf-pants',
      category: 'Pants',
      image: '/images/pant1.webp',
      image2: '/images/pant1-2.webp',
      image3: '/images/pant1-3.webp',
      price: 300,
      brand: 'Oliver',
      rating: '3.8',
      countInStock: 10,
      numReviews: 13,
      description: 'Smart looking paint',
    },
    {
      name: 'Fit Pant',
      slug: 'fit-pant',
      category: 'Pants',
      image: '/images/pant2.webp',
      image2: '/images/pant2-2.jpg',
      image3: '/images/pant2-3.webp',
      price: 100,
      brand: 'Zara',
      rating: '4',
      countInStock: 20,
      numReviews: 13,
      description: 'A popular pant',
    },
    {
      name: 'classic Pants',
      slug: 'classic-pant',
      category: 'Pants',
      image: '/images/pant3.webp',
      image2: '/images/pant3.webp',
      image3: '/images/pant3.webp',
      price: 100,
      brand: 'Oliver',
      rating: '3.8',
      countInStock: 10,
      numReviews: 13,
      description: 'Smart looking paint',
    },
  ],
};

export default data;
